.TH hyperspeed 6 "14 September 2025" "0.0.0.1"
.SH NAME
hyperspeed \- Galaxis community app
.SH SYNOPSIS
.SY hyperspeed
.OP \-\-help
.OP \-\-version
.YS
.SH DESCRIPTION
.B hyperspeed
makes it possible to reward members with engines
.SH OPTIONS
.TP
.BR \-\-help
Print a help message and exit.
.TP
.BR \-\-version
Display version information.
.SH EXIT STATUS
.B hyperspeed
always exits with status 0.
.SH COPYRIGHT
Copyright (c) 2025 Andras Kristof. This program is distributed under the MIT
license. See the file
.I LICENSE
distributed with this program for details.
